#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DOCS_DIR="$ROOT_DIR/docs"
FEATURES_DIR="$DOCS_DIR/features"
OUTPUT_FILE="$DOCS_DIR/registry/sync.md"

today="$(date '+%Y-%m-%d')"

feature_rows=""
status_counts=""
status_list=""
total_features=0
missing_assets=0
missing_summary=0
missing_detailed=0
missing_changelog=0

trim() {
  local value="$1"
  value="${value#"${value%%[![:space:]]*}"}"
  value="${value%"${value##*[![:space:]]}"}"
  printf '%s' "$value"
}

find_first_line() {
  local pattern="$1"
  local file="$2"

  if command -v rg >/dev/null 2>&1; then
    rg -N "$pattern" "$file" | head -n 1 || true
  else
    grep -E "$pattern" "$file" | head -n 1 || true
  fi
}

for dir in "$FEATURES_DIR"/*; do
  [[ -d "$dir" ]] || continue

  name="$(basename "$dir")"
  [[ "$name" == "_template" ]] && continue

  total_features=$((total_features + 1))

  summary_file="$dir/summary.md"
  detailed_file="$dir/detailed.md"
  changelog_file="$dir/changelog.md"
  assets_dir="$dir/assets"

  status="unknown"
  branch="-"
  headline="No summary available."

  if [[ -f "$summary_file" ]]; then
    status_line="$(find_first_line "^Status:" "$summary_file")"
    branch_line="$(find_first_line "^Branch:" "$summary_file")"
    headline_line="$(awk '
      BEGIN { capture=0 }
      /^One-line summary/ { capture=1; next }
      capture && /^-+$/ { next }
      capture && NF { print; exit }
    ' "$summary_file")"

    if [[ -n "$status_line" ]]; then
      status="$(trim "${status_line#Status:}")"
    fi
    if [[ -n "$branch_line" ]]; then
      branch="$(trim "${branch_line#Branch:}")"
    fi
    if [[ -n "$headline_line" ]]; then
      headline="$(trim "$headline_line")"
    fi
  else
    missing_summary=$((missing_summary + 1))
  fi

  status_list+="$status"$'\n'

  [[ -f "$detailed_file" ]] || missing_detailed=$((missing_detailed + 1))
  [[ -f "$changelog_file" ]] || missing_changelog=$((missing_changelog + 1))
  [[ -d "$assets_dir" ]] || missing_assets=$((missing_assets + 1))

  assets_state="yes"
  [[ -d "$assets_dir" ]] || assets_state="no"
  summary_state="yes"
  [[ -f "$summary_file" ]] || summary_state="no"
  detailed_state="yes"
  [[ -f "$detailed_file" ]] || detailed_state="no"
  changelog_state="yes"
  [[ -f "$changelog_file" ]] || changelog_state="no"

  feature_rows+="| $name | $status | $branch | $summary_state | $detailed_state | $changelog_state | $assets_state | $headline |\n"
done

if [[ -n "$status_list" ]]; then
  while IFS= read -r status_name; do
    [[ -n "$status_name" ]] || continue
    count="$(printf '%s' "$status_list" | awk -v target="$status_name" '$0 == target { count++ } END { print count + 0 }')"
    status_counts+="- ${status_name}: ${count}\n"
  done < <(printf '%s' "$status_list" | sort | uniq)
fi

cat > "$OUTPUT_FILE" <<EOF
# Documentation Sync

This file is generated by \`scripts/generate-docs-sync.sh\`. Do not edit it by hand unless you are intentionally changing the template logic.

## Snapshot

- Last generated: $today
- Total active feature folders: $total_features
- Missing \`summary.md\`: $missing_summary
- Missing \`detailed.md\`: $missing_detailed
- Missing \`changelog.md\`: $missing_changelog
- Missing \`assets/\`: $missing_assets

## Status Counts

$(printf '%b' "$status_counts")
## Review Checklist

- Confirm feature folders touched in the last merge still have accurate \`Status:\` values.
- Promote important decisions out of \`assets/\` into \`index.md\`, \`prd.md\`, \`design.md\`, or \`status.md\` when needed.
- Update the feature registry pages if a capability changed:
  - \`docs/registry/feature-catalog.md\`
  - \`docs/registry/features-by-status.md\`
  - \`docs/registry/capabilities-matrix.md\`
- Archive duplicate or superseded material if it is no longer part of the active narrative.

## Feature Audit

| Feature | Status | Branch | Summary | Detailed | Changelog | Assets | Summary Line |
| --- | --- | --- | --- | --- | --- | --- | --- |
$(printf '%b' "$feature_rows")
## How To Use

- Run this file generator after merging feature work.
- Treat missing files or stale statuses as review prompts, not necessarily failures.
- Keep \`assets/\` as preserved supporting context, but keep the current source of truth in the main feature docs.
EOF
